### ISSUE TITLE
Retrieving info about existing scenarios in a library

### ISSUE THREAD

**Issue by lucialayr** [syncrosim/pysyncrosim#64]
Hi,

I would like to use PySyncroSim to run scenarios from within an existing SyncroSim library through Python. I am looking for a way to
1. Get a list of all the scenarios existing in the library and
2. Get information about their specification

I set up SyncroSim like this (in Ubuntu)

```
import pandas as pd

import pysyncrosim as ps

my_session = ps.Session(location = "syncrosim_linux_3_0_9")

my_session.install_packages("helloworldTimePy")
my_session.install_packages("stsim")
```

and connect to the library like this

```
my_library = ps.library(name="MyExistingLibrary",
                        session=my_session,
                        packages=["helloworldTimePy", "stsim"])
```
where `MyExistingLibrary.ssim` lives in the same folder. 
 
How can I check, if the library is loaded correctly and if everything that should be in there, is present?

Thank you!

**Comment by diegobilski** [comment]
Hi @lucialayr,

you can see your library info with `my_library.info`, and you can check the scenarios in you library with `my_library.scenarios()`

[here](examples/spatial_demo.py) you can find a basic usage example of pysyncrosim.

Cheers,
